### ISSUE TITLE
[✔] Virtual HMD/Controller support?

### ISSUE THREAD

**Issue by g-coded** [infinitellamas/PSMS-OSVR-Connector#1] opened 2017-06-09 23:22 UTC
I was wondering if you saw the virtual hmd(ping pong led) was added to psms, and if you plan on implementing it.

**Comment by terminal29** [comment] 2017-06-11 04:01
Yes I'm planning to do a bit of a rewrite soon that will include support for this. I'm keen on using it as well :)

**Comment by g-coded** [comment] 2017-06-11 13:59
Thanks infinitellamas!  :)

**Comment by terminal29** [comment] 2017-06-12 12:50
Should be supported now. I have not tested it so tell me if it works or not.

**Comment by g-coded** [comment] 2017-06-13 00:17
Can't get it to work, getting a "Could not resolve source for /inf_osvr_move/MoveDevice/semantic/pingPongHMD
I've got psms tracking a ping pong ball(listing as device_id 0), not too sure what I'm missing.  Here is my [config file](https://pastebin.com/0L5kZJF2)

**Comment by terminal29** [comment] 2017-06-13 04:27
pingpongHMD/tracker to access the tracking information. (it doesnt have to be called pingpongHMD i was just using that as an example that the names can be whatever format you want)
Because you have enabled debug it should print the paths to console.

**Comment by L3nyxx** [comment] 2017-06-13 04:54
Hi infinitellamas. I am also getting the same error as g-coded even with "tracker" added. Here is my [config](https://pastebin.com/QdbKWVzf)

**Comment by terminal29** [comment] 2017-06-13 06:23
what paths does it print to the console for your HMD?
Here is what mine looks like
![image](https://user-images.githubusercontent.com/20899505/27068677-8671bf06-5054-11e7-93e6-b397e39795a3.png)

Edit: I'm sorry but I can't seem to replicate the problem. [This](https://pastebin.com/uGYLmdim) is the output from the osvr server, and [this](https://pastebin.com/67SdnSJ5) is my config file. Although i dont have any virtual HMD's hooked up, it doesn't complain about unconnected paths and I can view it in the tracker viewer fine.

**Comment by L3nyxx** [comment] 2017-06-13 07:07
I guess there was an error with my config. I copied your config and added in the arduino tracker and everything works now. Thanks!

**Comment by terminal29** [comment] 2017-06-13 07:09
Sweet. I'll be updating (rewriting) the arduino tracker soon as well so keep an eye out

**Comment by terminal29** [comment] 2017-06-13 07:12
I see your problem @L3nyxx, you had "params":{"params":{ ... so nothing was being linked. That's my fault though, ill edit the readme now. @g-coded that is your problem as well

**Comment by g-coded** [comment] 2017-06-13 11:58
@infinitellamas - I was using your config word for word(pingPongHMD) to avoid any syntax errors(don't want to trace down a missing character)
I will test out the new config file later today.

**Comment by g-coded** [comment] 2017-06-14 00:49
@infinitellamas - Getting the same error, now I'm not even sure what my config file should look like.(kept getting syntax errors)  Here is my current [config file](https://pastebin.com/U4CnhEUD).

**Comment by terminal29** [comment] 2017-06-14 00:54
/inf_osvr_move/MoveDevice/semantic/HMD should be 
/inf_osvr_move/MoveDevice/semantic/HMD/tracker

Each controller's base path contains no information, to access the device capabilities (tracker/buttons/analog data etc...) you need to link to the specific sub-path.

**Comment by g-coded** [comment] 2017-06-14 01:23
That got it working.  I was planning on just using psms for the tracking/buttons.  However I noticed my tracking spaces weren't alligning which is exactly what I was trying to get away from(osvr-kinect).  Do you think I'd have better luck including the controllers in this plugin.  It could also be steam vr telling me I need to run room setup(not sure why this came up?)

**Comment by terminal29** [comment] 2017-06-14 01:37
Currently the only way to use PSMove buttons with SteamVR is through PSMoveSteamVRBridge, OSVR-SteamVR driver doesn't support buttons and analogs (only head tracking). There has been a pull req open for a little over a year now that adds support, but I don't know if it will ever get merged. It is on my to-do list to make a workaround for this, and I can ping you if you want when i finish it.

**Comment by terminal29** [comment] 2017-06-15 06:29
Could either of you confirm if virtual HMD tracking works now so I can close the issue.
Cheers

**Comment by L3nyxx** [comment] 2017-06-15 06:35
I can confirm that the virtual hmd tracking is working fine for me. Tracks much better than the kinect v2. Thanks

**Comment by terminal29** [comment] 2017-06-15 06:37
That's great to hear. :)

**Closed as completed** 2017-06-15 06:37 UTC

**Comment by g-coded** [comment] 2017-06-15 06:50
Yes, working now thank you.  
@L3nyxx - I just tested this in steamvr compositor to confirm it was working, it's good to know it's working better than the kinect v2(what I'm trying to replace)
